### ISSUE TITLE
Archive not populating in Sandboxes, but works in PROD with same settings...

### ISSUE THREAD

**Issue by kurtfairfield** [j-fischer/rflib#62] opened 2022-07-01 19:24 UTC
**Describe the bug**
The Archive (big object) is not populating with records in a sandbox, even though cmdt settings are the same as in PROD which is working fine. But in sandbox, big object has no records in it at all, with Archive logging set to INFO.

**Version**
Was using 3.1.1, but upgraded to 4.0.0 (and 2.0.0 for both TS and FS successfully) problem persists in both versions.

**Expected behavior**
Archive should be populating. 

**Screenshots**
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/18200424/176955393-2cde41cf-9736-4f21-b41c-69cd29b7ab29.png">

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome
 - Version 103.0.5060.66

**Additional context**
Not sure what this is not working in the sandbox, but is working in PROD. All other sandboxes have same issue. Permission Set assigned to all users, with big object Logs Archive has Read and Create permissions. Perhaps there is some other configuration required in sandbox to make this work?

**Comment by j-fischer** [comment] 2022-07-04 03:58
Hi @kurtfairfield ,

This one is interesting. Could you please check the `RFLIB Log Event Handler` Flow for me and see if the latest version is the active one in the sandboxes? 

It should look like this: 

![image](https://user-images.githubusercontent.com/986653/177078864-441db0bd-202e-43a2-80d9-5c0223ea5d66.png)

If the flow version is correct, Did you by any chance receive an Flow error email? 

Thanks,
Johannes

**Comment by kurtfairfield** [comment] 2022-07-04 15:41
Seems like the most recent version 3 is active. Not seeing any flow error emails from from RFLIB in the sandboxes either...

<img width="1719" alt="image" src="https://user-images.githubusercontent.com/18200424/177185676-d76cca51-a235-472e-887d-5c8c1d67c5fc.png">

Let me know what else might be helpful in tracking this one down.

**Comment by kurtfairfield** [comment] 2022-07-04 21:14
@j-fischer - I am seeing this error in my Apex logs occasionally, in a sandbox...

```
55.0 APEX_CODE,DEBUG;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;NBA,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,INFO;WAVE,INFO;WORKFLOW,INFO
17:11:16.0 (560793)|USER_INFO|[EXTERNAL]|0051K000008fbLK|ghgsat_kf@silius.tech.233bulkwas|(GMT-04:00) Eastern Daylight Time (America/New_York)|GMT-04:00
17:11:16.0 (652213)|EXECUTION_STARTED
17:11:16.0 (663437)|CODE_UNIT_STARTED|[EXTERNAL]
17:11:16.0 (4543761)|SYSTEM_MODE_ENTER|false
17:11:16.0 (4620162)|SYSTEM_MODE_EXIT|false
17:11:16.0 (4782138)|SYSTEM_MODE_ENTER|false
17:11:16.0 (8657261)|SYSTEM_MODE_EXIT|false
17:11:16.0 (9038177)|FATAL_ERROR|System.SObjectException: Invalid field Logger_Factory_Class__c

Class.rflib_LoggerUtil.getFactory: line 47, column 1
Class.rflib_FeatureSwitchPlugin: line 36, column 1
17:11:16.0 (9463111)|CODE_UNIT_FINISHED
17:11:16.0 (9484399)|EXECUTION_FINISHED
```

**Comment by j-fischer** [comment] 2022-07-06 04:43
@kurtfairfield hm, ok, this is tricky. Could you pleases answer some of the following questions: 

1) When you don't see the errors in the Log Archive, do you still see the logs in the real-time/historic Log Monitor mode or are they missing there, too? 

2) Do all users have the proper permission sets assigned? The new Management Console can actually help with that is it will display you the users that are missing the proper permissions. Users must have access to the big object to allow for the creation of the records. However, I would expect a Flow error if that was not the case, hence another error in the logs. 

3) Could you paste a screenshot of your full logger settings here, org defaults and the list of the overrides? The Archive log level depends on the General Reporting Level. If Archive is set to INFO but the General setting is set to WARN, then the info statements would not be saved. 

4) The occasional error in the Apex logs, is there any pattern to it? For example, can it be reproduced for a specific users, not others, does sit happen for specific flows but not others? I would like to understand if there is a security/user context that could be missing access to the Custom Settings object. 

At this point, I have to assume that those two issues are unrelated as the error happens occasionally, while the Log Archive is never populated. The difference in timing here makes me think that there are two different problems at play here. 

Thanks

**Comment by kurtfairfield** [comment] 2022-07-11 16:31
@j-fischer 

1. We see logs in the original stream, but not stored in the new big object stream. So only missing in Archive.
2. All users have access to big object. Is there any other setting that I should check?
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/18200424/178312324-530bb398-85df-4371-8b15-c629b49c44c2.png">
3. Here is a screenshot from a sandbox (all sandboxes do not log to archive)
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/18200424/178312690-f2785d1a-c9b4-4e14-9df3-d67fc4aba6c6.png">
4. No pattern I can discern. But I have not looked for one really, just noticed it in passing. I will keep my eyes open for some root cause of the error, or if there are times when it does not happen or does happen.

Let me know if you need more information, happy to provide it.

**Comment by j-fischer** [comment] 2022-07-13 03:11
@kurtfairfield the Archive Log is dependent on a log event to be fired as the record is created in the After Save Flow Handler just before the Email notification is evaluated. 
The `Log Event Reporting Level` supersedes the `Archive Log Level` setting meaning that if the `Log Event Reporting Level` is set to `WARN`, the Archive Log is only able to capture WARN messages or higher. 

Could you please try to set the `Log Event Reporting Level` to `INFO` and see if that fixes the issue?

Thanks

<img width="459" alt="178312690-f2785d1a-c9b4-4e14-9df3-d67fc4aba6c6" src="https://user-images.githubusercontent.com/986653/178642374-2d7d7d68-14b1-4b6d-8490-60d15e3eb9ef.png">

**Comment by j-fischer** [comment] 2022-07-13 03:42
Hi @kurtfairfield , regarding the errors in the logs, I am not sure how much I can do here. Looking at the code, the message does not make sense from an application perspective. 

`17:11:16.0 (9038177)|FATAL_ERROR|System.SObjectException: Invalid field Logger_Factory_Class__c

Class.rflib_LoggerUtil.getFactory: line 47, column 1
Class.rflib_FeatureSwitchPlugin: line 36, column 1`

Looking at the code highlighted in the LoggerUtil class, I am using the Apex APIs to retrieve the Logger Settings instance. This should always return the same result from an object perspective. The values may be different based on the user context, but the structure of the returned object should be the same. 

`            rflib_Logger_Settings__c settings = rflib_Logger_Settings__c.getInstance();
    
            String loggerFactoryTypeName = settings != null && String.isNotBlank(settings.Logger_Factory_Class__c)`

The error indicates a programmatic issue where a field is accessed that does not exist. However, since the issue is only intermittent and the access is static and not dynamic, that argument has been disproven. 

At this point, looking at the log provided and the error thrown, I can only recommend to open a case with Salesforce. However, I would assume the case would be challenging to review with them as the issue is intermittent and the code belongs to a unlocked package. I would expect that Salesforce just points at me as the author and you'll be stuck in the middle. 

I am happy to help more but this may require the issue to be reproducible or I need more information about the execution context to investigate. I would recommend to focus this ticket on the Log Archive, and to open a new ticket should those errors persist and have any business impact. 

Thoughts?

**Comment by j-fischer** [comment] 2022-07-21 02:56
Hi @kurtfairfield , did my suggestion about the options solve your problem in the sandboxes?

**Comment by j-fischer** [comment] 2022-07-23 20:33
Closing the issue, feel free to reopen if the suggestions did not help. Thanks

**Closed by j-fischer** 2022-07-23 20:33 UTC
Labels: solution suggested

**Comment by kurtfairfield** [comment] 2022-08-08 23:51
@j-fischer - sorry for not replying here. I had a look at your proposed solution to up the level from WARN to INFO, but in my opinion, I should have been seeing WARN, ERROR and FATAL in the archive, but that was not happening.

I put this aside for a while, but have since updated the entire pipeline to the most recent versions, and now I was getting those WARN, ERROR and FATAL messages. And when I update to INFO, those are also logged to the archive. So not sure what the root cause was, but the issue is no more.

Thanks for you help:)
